#!/usr/bin/env python3
# foc_conf.py — read (and optionally patch) the VESC mc_configuration blob.
#
#   ./foc_conf.py [port]                  # read + decode, changes nothing
#   ./foc_conf.py [port] set-l <uH>       # patch ONLY foc_motor_l, write back
#
# Why patch-in-place instead of building a blob:
# COMM_SET_MCCONF is parsed with FIXED-WIDTH fields in a fixed order, so a
# single wrong width shifts every field after it — including l_current_max and
# l_abs_current_max, which are written to params UNCLAMPED (foc_esc.cpp:339).
# That is the top suspect for a destroyed power stage. So we never synthesize a
# config: we take the exact bytes the firmware just sent us, overwrite four
# bytes, and hand them back. Every field except the one we touched is
# guaranteed byte-identical to what the board already had.
#
# The offset table below is generated by replaying the SAME width sequence as
# VescTelemetry::handle_set_mcconf(), not by hand-counting.
import serial, struct, sys, time

COMM_SET_MCCONF = 13
COMM_GET_MCCONF = 14

# (name, kind) in blob order. kind: 'A'=f32_auto, 'u8','u16','u32','i32',
# ('h',scale)=int16/scale, ('b',n)=n raw bytes. Mirrors handle_set_mcconf().
FIELDS = [
    ("signature", "u32"),
    ("pwm_mode", "u8"), ("comm_mode", "u8"), ("motor_type", "u8"), ("sensor_mode", "u8"),
    ("l_current_max", "A"), ("l_current_min", "A"),
    ("l_in_current_max", "A"), ("l_in_current_min", "A"),
    ("l_in_current_map_start", ("h", 10000)), ("l_in_current_map_filter", ("h", 10000)),
    ("l_abs_current_max", "A"),
    ("l_min_erpm", "A"), ("l_max_erpm", "A"),
    ("l_erpm_start", ("h", 10000)),
    ("l_max_erpm_fbrake", "A"), ("l_max_erpm_fbrake_cc", "A"),
    ("l_min_vin", ("h", 10)), ("l_max_vin", ("h", 10)),
    ("l_battery_cut_start", ("h", 10)), ("l_battery_cut_end", ("h", 10)),
    ("l_battery_regen_cut_start", ("h", 10)), ("l_battery_regen_cut_end", ("h", 10)),
    ("l_slow_abs_current", "u8"),
    ("l_temp_fet_start", "u8"), ("l_temp_fet_end", "u8"),
    ("l_temp_motor_start", "u8"), ("l_temp_motor_end", "u8"),
    ("l_temp_accel_dec", ("h", 10000)),
    ("l_min_duty", ("h", 10000)), ("l_max_duty", ("h", 10000)),
    ("l_watt_max", "A"), ("l_watt_min", "A"),
    ("l_current_max_scale", ("h", 10000)), ("l_current_min_scale", ("h", 10000)),
    ("l_duty_start", ("h", 10000)),
    ("sl_min_erpm", "A"), ("sl_min_erpm_cycle_int_limit", "A"),
    ("sl_max_fullbreak_current_dir_change", "A"),
    ("sl_cycle_int_limit", ("h", 10)), ("sl_phase_advance_at_br", ("h", 10000)),
    ("sl_cycle_int_rpm_br", "A"), ("sl_bemf_coupling_k", "A"),
    ("hall_table", ("b", 8)),
    ("hall_sl_erpm", "A"),
    ("foc_current_kp", "A"), ("foc_current_ki", "A"),
    ("foc_f_zv", "A"), ("foc_dt_us", "A"),
    ("foc_encoder_inverted", "u8"),
    ("foc_encoder_offset", "A"), ("foc_encoder_ratio", "A"),
    ("foc_sensor_mode", "u8"),
    ("foc_pll_kp", "A"), ("foc_pll_ki", "A"),
    ("foc_motor_l", "A"),
    ("foc_motor_ld_lq_diff", "A"),
    ("foc_motor_r", "A"),
    ("foc_motor_flux_linkage", "A"),
]

WIDTH = {"u8": 1, "u16": 2, "u32": 4, "i32": 4, "A": 4}


def build_offsets():
    """Offset of each field, relative to the start of the blob (after cmd id)."""
    off, out = 0, {}
    for name, kind in FIELDS:
        out[name] = (off, kind)
        if isinstance(kind, tuple):
            off += 2 if kind[0] == "h" else kind[1]
        else:
            off += WIDTH[kind]
    return out


OFF = build_offsets()


def get_f32_auto(buf, i):
    (res,) = struct.unpack_from(">I", buf, i)
    e = (res >> 23) & 0xFF
    sig_i = res & 0x7FFFFF
    neg = bool(res & (1 << 31))
    sig = 0.0
    if e != 0 or sig_i != 0:
        sig = sig_i / (8388608.0 * 2.0) + 0.5
        e -= 126
    if neg:
        sig = -sig
    import math
    return math.ldexp(sig, e)


def put_f32_auto(value):
    import math
    sig, e = math.frexp(value)
    sig_abs = abs(sig)
    sig_i = 0
    if sig_abs >= 0.5:
        sig_i = int((sig_abs - 0.5) * 2.0 * 8388608.0)
        e += 126
    res = ((e & 0xFF) << 23) | (sig_i & 0x7FFFFF)
    if sig < 0.0:
        res |= 1 << 31
    return struct.pack(">I", res)


def read_field(blob, name):
    off, kind = OFF[name]
    if kind == "A":
        return get_f32_auto(blob, off)
    if kind == "u8":
        return blob[off]
    if kind == "u32":
        return struct.unpack_from(">I", blob, off)[0]
    if isinstance(kind, tuple):
        if kind[0] == "h":
            return struct.unpack_from(">h", blob, off)[0] / kind[1]
        return list(blob[off:off + kind[1]])
    return None


def crc16(d):
    c = 0
    for b in d:
        c ^= b << 8
        for _ in range(8):
            c = ((c << 1) ^ 0x1021) & 0xFFFF if c & 0x8000 else (c << 1) & 0xFFFF
    return c


def frame(payload):
    if len(payload) <= 255:
        head = bytes([2, len(payload)])
    else:
        head = bytes([3, len(payload) >> 8, len(payload) & 0xFF])
    return head + payload + struct.pack(">H", crc16(payload)) + b"\x03"


def read_packet(ser, deadline):
    """Read one VESC frame, short (0x02) or long (0x03)."""
    while time.time() < deadline:
        b = ser.read(1)
        if not b:
            continue
        if b[0] == 2:
            h = ser.read(1)
            if not h:
                return None
            n = h[0]
        elif b[0] == 3:
            h = ser.read(2)
            if len(h) < 2:
                return None
            n = (h[0] << 8) | h[1]
        else:
            continue
        p = ser.read(n)
        tail = ser.read(3)
        if len(p) == n and len(tail) == 3 and tail[2] == 0x03:
            if crc16(p) == ((tail[0] << 8) | tail[1]):
                return p
    return None


PORT = sys.argv[1] if len(sys.argv) > 1 else "/dev/ttyACM0"
CMD = sys.argv[2].lower() if len(sys.argv) > 2 else "read"

ser = serial.Serial(PORT, 115200, timeout=0.2)
ser.reset_input_buffer()
ser.write(frame(bytes([COMM_GET_MCCONF])))
pkt = read_packet(ser, time.time() + 3.0)

if pkt is None or len(pkt) < 200 or pkt[0] != COMM_GET_MCCONF:
    print(f"no valid MCCONF reply (got {0 if pkt is None else len(pkt)} B)")
    ser.close()
    sys.exit(1)

blob = pkt[1:]           # strip the command-id byte
print(f"MCCONF blob: {len(blob)} B   signature 0x{read_field(blob,'signature'):08X}\n")

SHOW = [
    ("l_current_max",          "A",   "FOC_I_MAX",    15.0),
    ("l_abs_current_max",      "A",   "FOC_I_OCHARD", 45.0),
    ("l_max_vin",              "V",   "FOC_V_MAX",    40.0),
    ("l_temp_fet_start",       "C",   "FOC_T_START",  None),
    ("l_temp_fet_end",         "C",   "FOC_T_MAX",    None),
    ("l_max_duty",             "",    "duty_max",     None),
    ("foc_motor_l",            "H",   "FOC_M_LS",     80e-6),
    ("foc_motor_r",            "ohm", "FOC_M_RS",     0.055),
    ("foc_motor_flux_linkage", "Wb",  "FOC_M_FLUX",   4.6e-3),
    ("foc_sensor_mode",        "",    "0=sensorless 1=encoder 2=hall", None),
    ("foc_current_kp",         "",    "derived",      None),
    ("foc_current_ki",         "",    "derived",      None),
]
ok = True
for name, unit, param, expect in SHOW:
    v = read_field(blob, name)
    flag = ""
    if expect is not None:
        # Sanity: does the decode match the firmware's known value? If these
        # line up, the offset map is proven and a patch can be trusted.
        rel = abs(v - expect) / max(abs(expect), 1e-12)
        flag = "  <-- MISMATCH" if rel > 0.02 else "  ok"
        if rel > 0.02:
            ok = False
    print(f"  {name:<24} = {v:<14.6g} {unit:<4} [{param}]{flag}")
print(f"  {'hall_table':<24} = {read_field(blob,'hall_table')}")

if CMD == "read":
    print("\n(read only — nothing written)")
    ser.close()
    sys.exit(0 if ok else 2)

if CMD == "set-l":
    if not ok:
        print("\nREFUSING to write: decode did not match expected values, so the\n"
              "offset map is wrong and a patch would corrupt other fields.")
        ser.close()
        sys.exit(2)
    uh = float(sys.argv[3])
    new_l = uh * 1e-6
    off, _ = OFF["foc_motor_l"]
    patched = bytearray(blob)
    patched[off:off + 4] = put_f32_auto(new_l)
    # Prove exactly four bytes moved, and that they decode to what we intended.
    diff = [i for i in range(len(blob)) if blob[i] != patched[i]]
    check = get_f32_auto(bytes(patched), off)
    print(f"\npatch: foc_motor_l {read_field(blob,'foc_motor_l')*1e6:.2f} uH "
          f"-> {check*1e6:.2f} uH")
    print(f"bytes changed: {diff} (expected exactly {list(range(off, off+4))})")
    if diff != list(range(off, off + 4)):
        print("REFUSING to write: unexpected byte diff")
        ser.close()
        sys.exit(2)
    ser.write(frame(bytes([COMM_SET_MCCONF]) + bytes(patched)))
    time.sleep(0.3)
    print("written — board reboots to apply; re-run 'read' to confirm")
    ser.close()
    sys.exit(0)

print(f"unknown command '{CMD}' (use: read | set-l <uH>)")
ser.close()
sys.exit(1)
